### ISSUE TITLE
how to upload?

### ISSUE THREAD

**Issue by ucalyptus2** [wldhx/yadisk-direct#2]

**Comment by eldarbr** [comment]
Hello
This module does not enable you to upload files to yandex disk. If you want to upload files, see yandex api docs:
https://yandex.com/dev/disk/api/reference/upload.html

**Comment by wldhx** [comment]
Sorry @forkbabu, missed the question at the time; and thanks @eldarbr for the answer!

If someone has an impl, I'd be happy to merge a PR in,
